name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-12
    name: 3.1
    steps:
    - uses: actions/checkout@v2
    - name: OpenBSD Test
      id: test
      uses: vmactions/openbsd-vm@v0.0.6
      with:
        prepare: |
          pkg_add ruby31-rake-compiler
          gem31 install -N minitest-global_expectations
        run: |
          rake31
